title: CV Arxiv Daily
description: Automatically Update CV Papers Daily using Github Actions (Update Every 23th hours)
show_downloads: true

github:
  zip_url: https://github.com/yangzj6677/cv-arxiv-daily
  another_url: https://github.com/yangzj6677/cv-arxiv-daily

## add remote theme
remote_theme: jekyll/minima@v2.5.1

# minima:
skin: dark
social_links:
  github: yangzj6677

plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag
